[package]
name = "space-invader"
version = "0.1.0"
edition = "2021"


[profile.dev.package."*"]
opt-level = 3

[package.metadata.docs.rs]
all-features = true


[dependencies]
rand = "0.8.5"
macroquad = "0.4.2"
egui = "0.22.0"

